### ISSUE TITLE
Screen freezes on loading

### ISSUE THREAD

**Issue by aecarvalho** [TeamWin/android_device_xiaomi_beryllium#6]
This is by far the most common issue that on loading TWRP 3.3 on beryllium, the screen remains frozen for at least 5 seconds at the menu page, there have been no fixes yet nor has it been reported as an issue here hence raising it.
Hope it gets fixed if there's an update, thanks for the great work done to make this recovery almost flawless.

**Comment by gongoscho** [comment]
Do you have the Problem with the latest [v3.4](https://dl.twrp.me/beryllium/twrp-3.4.0-0-beryllium.img.html) from 2020-10-24?

grEEtZ

**Comment by aecarvalho** [comment]
I just noticed that Beryllium recovery is being supported again and 3.4 has been released, just installed it today so will update on it after a few days of use, for now closing the issue as it's inapplicable to the present version.
