### ISSUE TITLE
Shows E: recv error on uevent sometimes

### ISSUE THREAD

**Issue by aecarvalho** [TeamWin/android_device_xiaomi_beryllium#7]
This is not a recurring issue but last time I tried to create a system+vendor+data+boot backup directly to my external SD card, E: recv error on uevent kept popping up, it was showing up since the time I booted TWRP and kept popping up all the time between the backup process.

![IMG_20200726_001856](https://user-images.githubusercontent.com/60945000/88882335-58a9e500-d24f-11ea-9afa-ef13b2c82b1f.jpg)

**Comment by bigbiff** [comment]
This was fixed in 3.4. The log level was set to high.
