### ISSUE TITLE
Issue #7 is unresolved as TWRP 3.4 isn't available for beryllium

### ISSUE THREAD

**Issue by aecarvalho** [TeamWin/android_device_xiaomi_beryllium#8]
This was fixed in 3.4. The log level was set to high.

_Originally posted by @bigbiff in https://github.com/TeamWin/android_device_xiaomi_beryllium/issues/7#issuecomment-666384388_

Sorry for having to reopen the issue as a new issue but as you can observe there has been no development to the beryllium TWRP since January 2019, hence TWRP 3.4 isn't available, therefore the issue remains unresolved.

**Comment by gongoscho** [comment]
TWRP 3.4 for Xiaomi POCO / Pocophone F1 (codenamed "beryllium") is released: https://dl.twrp.me/beryllium/twrp-3.4.0-0-beryllium.img.html

grEEtZ,
gongoscho

**Comment by aecarvalho** [comment]
Thanks for bringing it to my notice, very grateful to the developer who started supporting it after so long.
